version: '3'

services:
  db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: postgres:14-alpine
    ports:
      - "5432:5432"
  web:
    restart: on-failure
    depends_on:
      - db
    build: .
    environment:
      ROCKET_ENV: development
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    ports:
      - "8080:8080"

networks:
  default:
    ipam:
      config:
      - subnet: 172.30.0.0/16
